### ISSUE TITLE
Bootloader message types (0x60...0x64) are not documented

### ISSUE THREAD

**Issue by nagisa** [velbus/moduleprotocol#4]
Currently when you right-click a module in Velbus-Link and request a module to be rebooted it sends a sequence of packets with IDs `0x60` to enter the bootloader to `0x64` to exit it.

I found myself needing to restart two modules at once-ish to test their combined behaviour after a power loss (something Velbus Link does not have an ability to do,) but was not able to find the relevant information on the message types in question in the documentation in order to implement this.

vmb1rynos, vmbpiro are the ones I was looking for, but I also checked a more recent -20 module manual and it still lacks the relevant information.

Would it be possible to have the module documentation extended to include documentation for the bootloader messages?

**Comment by silamon** [comment]
The bootloader and firmware parts are not documented.
